### ISSUE TITLE
no NC format drill file

### ISSUE THREAD

**Issue by aaronvt** [nist-ionstorage/digital-servo#1]
I dont have altium, but would like to make a few copies from somewhere like OSHPark.com.  It reads al the gerbers correctly, but says there is no drills, it needs them in NC format not the altium GG1 DD1 , would it be possible to add a compatible NC drill file?

http://support.oshpark.com/support/solutions/articles/136065-altium-drill-files

**Comment by dleibrandt** [comment]
Sure thing.  I think I've gotten all the settings correct now.  See:
/hardware/Project Outputs for OK6010_DB/OK6010_DB.TXT
