### ISSUE TITLE
testing RJ45 and digital connectors

### ISSUE THREAD

**Issue by jbqubit** [nist-ionstorage/digital-servo#3]
@dleibrandt Does GUI include provision to test connectivity of RJ45 an digital IO connectors? technosystem would like to make simple test to validate assembled units.

**Comment by dleibrandt** [comment]
RJ45 - Not presently, although it wouldn't be too difficult to put something in.  Did you have anything in particular in mind?

Digital IO - Yes, but not in the standard version of the firmware.  For testing, I use a different firmware, which I just uploaded to [here](https://github.com/nist-ionstorage/digital-servo/blob/master/deploy/Windows7_FW28may15/superlaserland_HW07jun12_CONFIG_TESTHARDWARE_FW20mar15.bit).  In it, there is no GUI settable configuration.  Instead, the outputs mirror the inputs as follows:

AOUT0,1 and AIN0,1 are set to +/- 4 V range 
AOUT0 = AIN0 
AOUT1 = AIN1 
AOUT2 = AIN1 
DOUTx = DINx 
LEDs = orange

**Comment by jbqubit** [comment]
> Digital IO - Yes, but not in the standard version of the firmware.
> outputs mirror the inputs

Perfect. That's a good test. And nice that it doesn't require interaction
with the GUI.

For testing RJ45, a simple functionality test is AUX1 output mirroring AUX0
input. If you have bandwidth please generate a firmware that adds this
test. This will put technosystem in a good position to build and test boxes
for many groups. :)

-Joe




Joe Britton
Sensors and Electron Devices
Army Research Lab
2800 Powder Mill Rd
Adelphi, MD 20783
301-394-3130
joseph.w.britton5.civ@mail.mil
