### ISSUE TITLE
Matlab script for measuring transfer function 

### ISSUE THREAD

**Issue by daiweizhu** [nist-ionstorage/digital-servo#4]
@dleibrandt  Can you share a sample script for calculating the transfer function from the files generated by the "measure transfer function" tool in GUI? I was able to read in single files in Matlab with the readSuperLaserLandSimplePI. But I don't know how to combine all the files.
Thanks a lot!

**Comment by dleibrandt** [comment]
See https://github.com/nist-ionstorage/digital-servo/blob/master/matlab/plotTransferFunction.m.
